import type { FieldDef } from "@/components/entity-form";
import {
  BUSINESS_TYPES,
  BUYER_STATUS,
  CERTIFICATIONS,
  INCOTERMS,
  PAYMENT_TERMS,
  PRODUCER_CONTRACT_STATUS,
  PRODUCT_CATEGORIES,
  PRODUCT_STATUS,
  STORAGE_TEMPS,
} from "./constants";

export const PRODUCER_FIELDS: FieldDef[] = [
  { key: "code", label: "Producer ID", type: "text", section: "基本情報", hint: "空欄なら自動採番" },
  { key: "company_name", label: "会社名", type: "text", section: "基本情報", required: true },
  { key: "brand_name", label: "ブランド名", type: "text", section: "基本情報" },
  { key: "contact_name", label: "担当者", type: "text", section: "基本情報" },
  { key: "phone", label: "電話番号", type: "tel", section: "基本情報" },
  { key: "email", label: "Email", type: "email", section: "基本情報" },
  { key: "prefecture", label: "都道府県", type: "text", section: "基本情報" },
  { key: "address", label: "所在地", type: "text", section: "基本情報", span: 2 },
  { key: "website", label: "Webサイト", type: "url", section: "基本情報" },
  { key: "categories", label: "商品カテゴリー", type: "multi", options: PRODUCT_CATEGORIES, section: "商品・供給", span: 3 },
  { key: "main_products", label: "取扱商品", type: "textarea", section: "商品・供給", span: 2 },
  { key: "sku_count", label: "SKU数", type: "number", section: "商品・供給" },
  { key: "wholesale_price", label: "卸価格", type: "text", section: "商品・供給", placeholder: "例：1kg ¥4,200〜" },
  { key: "moq", label: "MOQ", type: "text", section: "商品・供給" },
  { key: "capacity", label: "生産能力", type: "text", section: "商品・供給", placeholder: "例：月 5t" },
  { key: "inventory", label: "在庫", type: "text", section: "商品・供給" },
  { key: "shelf_life", label: "賞味期限", type: "text", section: "商品・供給" },
  { key: "storage_temp", label: "保存温度", type: "select", options: STORAGE_TEMPS, section: "商品・供給" },
  { key: "export_experience", label: "輸出経験", type: "text", section: "輸出対応", placeholder: "例：あり（香港・台湾）" },
  { key: "available_countries", label: "対応可能国", type: "countries", section: "輸出対応", span: 3 },
  { key: "certifications", label: "HACCP等認証", type: "multi", options: CERTIFICATIONS, section: "輸出対応", span: 3 },
  { key: "image_url", label: "商品画像", type: "file", section: "資料" },
  { key: "docs_url", label: "商品資料", type: "file", section: "資料" },
  { key: "contract_status", label: "契約状況", type: "select", options: PRODUCER_CONTRACT_STATUS, section: "契約・営業" },
  { key: "commission_rate", label: "手数料率", type: "number", suffix: "%", section: "契約・営業" },
  { key: "last_contact_at", label: "最終連絡日", type: "date", section: "契約・営業" },
  { key: "next_action", label: "次回アクション", type: "text", section: "契約・営業", span: 2 },
  { key: "next_action_date", label: "次回アクション日", type: "date", section: "契約・営業" },
  { key: "notes", label: "メモ", type: "textarea", section: "契約・営業", span: 3 },
];

export const BUYER_FIELDS: FieldDef[] = [
  { key: "code", label: "Buyer ID", type: "text", section: "企業情報", hint: "空欄なら自動採番" },
  { key: "company_name", label: "企業名", type: "text", section: "企業情報", required: true },
  { key: "business_type", label: "業態", type: "select", options: BUSINESS_TYPES, section: "企業情報" },
  { key: "country", label: "国", type: "country", section: "企業情報", placeholder: "自動判定（電話・Email）", hint: "空欄なら電話番号・Emailドメインから自動設定" },
  { key: "city", label: "都市", type: "text", section: "企業情報" },
  { key: "website", label: "Webサイト", type: "url", section: "企業情報" },
  { key: "contact_name", label: "担当者", type: "text", section: "担当者" },
  { key: "position", label: "Position", type: "text", section: "担当者" },
  { key: "email", label: "Email", type: "email", section: "担当者" },
  { key: "phone", label: "Phone", type: "tel", section: "担当者", placeholder: "+65 ..." },
  { key: "whatsapp", label: "WhatsApp", type: "tel", section: "担当者" },
  { key: "linkedin", label: "LinkedIn", type: "url", section: "担当者" },
  { key: "desired_products", label: "希望商品", type: "textarea", section: "取引条件", span: 3 },
  { key: "price_range", label: "希望価格帯", type: "text", section: "取引条件" },
  { key: "desired_moq", label: "希望MOQ", type: "text", section: "取引条件" },
  { key: "incoterms", label: "Incoterms", type: "select", options: INCOTERMS.map((i) => ({ value: i.key, label: i.key })), section: "取引条件" },
  { key: "payment_terms", label: "Payment Terms", type: "select", options: PAYMENT_TERMS, section: "取引条件" },
  { key: "import_history", label: "輸入実績", type: "textarea", section: "取引条件", span: 2 },
  { key: "status", label: "商談Status", type: "select", options: BUYER_STATUS, section: "営業管理" },
  { key: "last_contact_at", label: "最終接触日", type: "date", section: "営業管理" },
  { key: "next_contact_at", label: "次回Contact日", type: "date", section: "営業管理" },
  { key: "notes", label: "メモ", type: "textarea", section: "営業管理", span: 3 },
];

export const PRODUCT_FIELDS: FieldDef[] = [
  { key: "code", label: "Product ID", type: "text", section: "基本情報", hint: "空欄なら自動採番" },
  { key: "producer_id", label: "Producer", type: "ref", section: "基本情報", required: true },
  { key: "name", label: "商品名", type: "text", section: "基本情報", required: true },
  { key: "name_en", label: "商品名（英語）", type: "text", section: "基本情報" },
  { key: "category", label: "Category", type: "select", options: PRODUCT_CATEGORIES, section: "基本情報", hint: "空欄なら Producer から自動設定" },
  { key: "status", label: "Status", type: "select", options: PRODUCT_STATUS, section: "基本情報" },
  { key: "sku", label: "SKU", type: "text", section: "コード" },
  { key: "jan", label: "JAN", type: "text", section: "コード" },
  { key: "hs_code", label: "HS Code", type: "text", section: "コード", placeholder: "0307.22" },
  { key: "ingredients", label: "原材料", type: "textarea", section: "仕様", span: 2 },
  { key: "net_content", label: "内容量", type: "text", section: "仕様" },
  { key: "case_qty", label: "ケース入数", type: "number", section: "仕様" },
  { key: "weight_kg", label: "重量", type: "number", suffix: "kg", section: "仕様" },
  { key: "size", label: "サイズ", type: "text", section: "仕様", placeholder: "W×D×H cm" },
  { key: "shelf_life", label: "賞味期限", type: "text", section: "仕様" },
  { key: "storage", label: "保存方法", type: "select", options: STORAGE_TEMPS, section: "仕様" },
  { key: "cost_price", label: "原価", type: "number", suffix: "円", section: "価格" },
  { key: "domestic_wholesale_price", label: "国内卸価格", type: "number", suffix: "円", section: "価格" },
  { key: "export_price", label: "輸出価格", type: "number", suffix: "円", section: "価格" },
  { key: "moq", label: "MOQ", type: "number", section: "価格" },
  { key: "certifications", label: "Certification", type: "multi", options: CERTIFICATIONS, section: "輸出", span: 3 },
  { key: "export_restrictions", label: "Export Restrictions", type: "textarea", section: "輸出", span: 3 },
  { key: "target_countries", label: "対応国", type: "countries", section: "輸出", span: 3 },
  { key: "image_url", label: "商品画像", type: "file", section: "多言語・素材" },
  { key: "description_en", label: "英語説明", type: "textarea", section: "多言語・素材", span: 3 },
  { key: "description_zh", label: "中国語説明", type: "textarea", section: "多言語・素材", span: 3 },
  { key: "description_ko", label: "韓国語説明", type: "textarea", section: "多言語・素材", span: 3 },
];
